#ifndef title.h
#define title.h

#include<stdio.h>
#include<conio.h>
#include<bios.h>
#include<fcntl.h>
#include<io.h>
#include<stdio.h>
#include<conio.h>
#include<string.h>
#include<bios.h>
#include<math.h>
#include<time.h>

#include"bricwall.h"
#include"chat.h"
#include"chatHanz.h"
#include"chatInpu.h"
#include"chatQhwh.h"
#include"chatShow.h"
#include"color1.h"
#include"findway.h"
#include"finger.h"
#include"frnture.h"
#include"hzxs.h"
#include"input.h"
#include"iph_page.h"
#include"log_in.h"
#include"main_.h"
#include"main2.h"
#include"manbody.h"
#include"module_b.h"
#include"mouse.h"
#include"myhouse.h"
#include"rbtbody.h"
#include"rbtfunc.h"
#include"rbtmove.h"
#include"register.h"
#include"sdzl.h"
#include"svgahead.h"
#include"timeline.h"
#include"typstrct.h"
#include"userlist.h"
#include"welcome.h"
#include"advance.h"
#include"basicgf.h"
#include"set_c.h"
#include"txt_save.h"

#define ORIGINX 767
#define ORIGINY 4
#define FINALX 1020
#define FINALY 547
#define MIDDLEX 894
#define ROBOTx 894
#define ROBOTy 404
#define TRUE 1
#define xmi 1
#define xma 1024
#define ymi 1
#define yma 767
#define PI 3.1415926
#define WITHOUT_THING 0
#define WITH_BOTTLE 1
#define WITH_CLOTHES 2
#define WITH_PLATE 3
#define MAXTXT 1000

#define MAN 1       //寻路用
#define ROBOT 0

#define INTRADER 0
#define MASTER 1
//关于颜色的说明
#define HAIRM 41605	//主人的头发，赭黄
#define SKINM 63222	//主人的皮肤，小麦色
#define EYESM 65535	//主人的眼睛，蓝
#define ARMSM 65504	//主人的手臂，黄
#define PANTSM 29186	//主人的裤子，乌贼墨色

#define HAIRI 48006	//入侵者的头发，古铜色
#define SKINI 63222	//入侵者的皮肤，小麦色
#define EYESI 65535	//入侵者的眼睛，蓝
#define ARMSI 64342	//入侵者的手臂，暖粉红
#define PANTSI 52625	//入侵者的裤子，灰土色
#define PI 3.1415926
#define YG 40
#define M 4
#define UP 1
#define LEFT 2
#define DOWN 3
#define RIGHT 4
#define UP_DOWN 5
#define LEFT_RIGHT 6

#endif // _TITLE_H_
